# Generated by Django 2.0.1 on 2021-07-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userentity',
            table='app_user',
        ),
    ]
