# Generated by Django 2.0.1 on 2021-07-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210714_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='成立时间'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='d35c6bc28d58450292293212d91c65d2', primary_key=True, serialize=False, verbose_name='商店号'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='last_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后变更时间'),
        ),
    ]
