# Generated by Django 2.0.1 on 2021-07-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210714_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitentity',
            name='fruit_picture',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='fruit', verbose_name='picture', width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='fruitentity',
            name='logo_height',
            field=models.IntegerField(null=True, verbose_name='picture高'),
        ),
        migrations.AddField(
            model_name='fruitentity',
            name='logo_width',
            field=models.IntegerField(null=True, verbose_name='picture宽'),
        ),
    ]
