# Generated by Django 2.0.1 on 2021-07-16 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210716_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitCartEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1, verbose_name='数量')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CartEntity', verbose_name='购物车')),
            ],
            options={
                'verbose_name': '购物车详情表',
                'verbose_name_plural': '购物车详情表',
                'db_table': 't_fruit_cart',
            },
        ),
        migrations.AlterModelTable(
            name='fruitentity',
            table='t_fruit',
        ),
        migrations.AddField(
            model_name='fruitcartentity',
            name='fruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FruitEntity', verbose_name='水果名'),
        ),
    ]
